all: compilar
compilar: propiedad inmobiliaria  main
		g++ -o a propiedad.o inmobiliaria.o main.o
propiedad: propiedad.cpp propiedad.h
		g++ -c propiedad.cpp
inmobiliaria: inmobiliaria.cpp inmobiliaria.h
		g++ -c inmobiliaria.cpp
main: main.cpp 
	  g++ -c main.cpp
