all: programa
programa: circulo rectangulo triangulo main
	g++ -o Ejecutable circulo.o rectangulo.o triangulo.o main.o
circulo: circulo.cpp
	g++ -c circulo.cpp
rectangulo: rectangulo.cpp
	g++ -c rectangulo.cpp
triangulo: triangulo.cpp
	g++ -c triangulo.cpp
main: main.cpp
	g++ -c main.cpp